### ISSUE TITLE
How can I use it ?

### ISSUE THREAD

**Issue by marabesi** [quack/try-online#1]
Is there any tutorial to run it ?

**Comment by haskellcamargo** [comment]
Well, you can download the files and put them on a local or remote server. When you run the `index.html`, it will open a in-browser-REPL for you. You can also try it on my [temporary server](http://108.167.188.125/~conta180/quack/)! Please, note the files are not updated and the language spec is in constant changes. In the web REPL, I'm _only_ generating the AST because the Python and PHP codegen are not fully implemented in order to test yet.

**Comment by marabesi** [comment]
tks !
